services:
  app:
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://0.0.0.0:8000/healthcheck/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    build:
      context: ./app
      dockerfile: ./dev.Dockerfile
    container_name: "app"
    command: /bin/sh /app/django-entrypoint.dev.sh
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - app/.env
