services:
  app:
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://0.0.0.0:8000/healthcheck/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    build:
      context: ./app
      dockerfile: ./prod.Dockerfile
    command: /bin/sh /app/django-entrypoint.prod.sh
    container_name: "app"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - 8000
    env_file:
      - app/.env.prod

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/django/staticfiles
      - media_volume:/home/app/django/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      vpn_panel:
        condition: service_healthy


  nginx-proxy-letsencrypt:
    container_name: "letsencrypt"
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      vpn_panel:
        condition: service_healthy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:


